#global:
#  scrape_interval: 10s
#  scrape_timeout: 5s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    dns_sd_configs:
      - names: ['online-shop']
        type: 'A'
        port: 8080
    scrape_interval: 5s
  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
    scrape_interval: 5s
